### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'call')     at Hash.CipherBase

### ISSUE THREAD

**Issue by SanumNisar** [crypto-browserify/createHash#30]
I am using this createHash package in my code. The problem is it works fine for the algorithms i.e.  'md5', 'rmd160' and 'ripemd160' however for the sha algorithms, I am getting the error:

const hash = createHash('sha256')
    .update(entropyBuffer)
    .digest();

Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at Hash.CipherBase (index.js:7:1)
    at new Hash (browser.js:9:1)
    at createHash (browser.js:29:1)
    at deriveChecksumBits (bip39.ts:90:1)
    at entropyToMnemonic (bip39.ts:45:1)
    at generateMnemonic (bip39.ts:17:1)
    at Home.tsx:25:1
    at IonLifeCycleContext.tsx:67:1
    at Array.forEach (<anonymous>)
    at DefaultIonLifeCycleContext.ionViewWillEnter

**Comment by justinr1234** [comment]
This is because you're using it in the browser. This thread has a solution: https://github.com/crypto-browserify/cipher-base/issues/11
